[options]
use_instance = true

[icons]
TelegramDesktop = "ï‹†"
firefox = "ï‰©"
discord = "ï’"
Alacritty = "ï„ "
kitty = "ï„ "
Steam = "ï†¶"
chatterino = "ï‚†"
jetbrains-rider = "ï„¡"
jetbrains-goland = "ï„¡"
jetbrains-clion = "ï„¡"
jetbrains-idea = "ï„¡"
jetbrains-webstorm = "ï„¡"
KeePassXC = "ï‚„"
st-256color = "ï„ "
vlc = "ï‹"
mpv = "ï‹"
kawaii-player = "ï‹"
Slack = "ï¯"
Thunderbird = "ïƒ "
minecraft-launcher = "ï†²"
streamlink-twitch-gui = "ï‡¨"
MyNiceProgram = "ğŸ˜›"
"Minecraft* 1.16.1" = "ï†²"
"Ledger Live" = "ï¹"
qBittorrent = "ï€™"
steam_app_438100 = "ï„›"
steam_app_39210 = "ï„›"
vrcapiary = "ï†ˆ"
jetbrains-toolbox = "ï†²"
ranger = "ï¼"
net-runelite-client-RuneLite = "ï„›"
net-runelite-launcher-Launcher = "ï„›"
"ffxiv_dx11.exe" = "ï„›"
looking-glass-client = "ï…º"

[aliases]
gl = "mpv"
nwjs_kjlcknihpadniagphehmpojkkdigigjp = "Twitch"
Navigator = "Firefox"
slack = "Slack"
steam_proton = "Proton"
"advanced combat tracker.exe" = "ACT"
Alacritty = "st"
kitty = "Kitty"
vrcapiary = "VRCApiary"
streamlink-twitch-gui = "Twitch"
steam_app_438100 = "VRChat"
"ffxiv_dx11.exe" = "Final Fantasy XIV"
steam_app_282800 = "100% Orange Juice"
"Ledger Live" = "Ledger"
"Minecraft* 1.16.1" = "Minecraft"
minecraft-launcher = "Minecraft"
chatterino = "Chatterino"
vlc = "VLC"
kawaii-player = "Kawaii"
firefox = "Firefox"
discord = "Discord"
st-256color = "st"
jetbrains-toolbox = "Toolbox"
jetbrains-rider = "Rider"
jetbrains-goland = "GoLand"
jetbrains-clion = "CLion"
jetbrains-idea = "IntelliJ IDEA"
jetbrains-webstorm = "WebStorm"
ranger = "Ranger"
net-runelite-client-RuneLite = "RuneLite"
net-runelite-launcher-Launcher = "RuneLite"
looking-glass-client = "Wangblows 10"
